"""Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

highest = 4000000 # 4 million

total = 0

prev = 0
n = 1
while True:
    f = n + prev
    if f > highest:
        break
    print '%d is a f number' % f
    if f % 2 == 0:
        total += f
    prev = n
    n = f
print total
